name: Deploy Astro site to GitHub Pages

on:
  push:
    branches:
      - main  # Reemplaza 'main' con la rama que uses
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: withastro/action@v2
        with:
          node-version: '20'  # O la versión que uses

      - name: Install dependencies
        run: npm install

      - name: Build Astro project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Reemplaza 'dist' si tu directorio de salida es diferente
